export enum HfActions
{
	ADD_HFPLANTACION = "ADD_HFPLANTACION"
	, EDIT_HFPLANTACION = "EDIT_HFPLANTACION"
	, REMOVE_HFPLANTACION = "REMOVE_HFPLANTACION"
}

export enum HfFilters
{
	SET_HFTIPO = "SET_HFTIPO"
	, SET_HFGERMINACION = "SET_HFGERMINACION"
	, SORTBY_HFTIPO = "SORTBY_HFTIPO"
	, SORTBY_HFGERMINACION = "SORTBY_HFGERMINACION"
}

export enum HfSortby
{
	HFTIPO = "HFTIPO"
	, HFGERMINACION = "HFGERMINACION"
}
