export enum HfActions
{
	ADD_HFPLANTACION = "ADD_HFPLANTACION"
	, EDIT_HFPLANTACION = "EDIT_HFPLANTACION"
	, REMOVE_HFPLANTACION = "REMOVE_HFPLANTACION"
}

export enum HfFilters
{
	SET_HFTIPO = "SET_HFTIPO"
	, SET_HFCANTIDAD = "SET_HFCANTIDAD"
	, SET_HFGERMINACION = "SET_HFGERMINACION" // https://huertify.atlassian.net/browse/HTFY-54

	, SORTBY_HFTIPO = "SORTBY_HFTIPO"
	, SORTBY_HFCANTIDAD = "SORTBY_HFCANTIDAD"
	, SORTBY_HFGERMINACION = "SORTBY_HFGERMINACION" // https://huertify.atlassian.net/browse/HTFY-54
}

export enum HfSortby
{
	HFTIPO = "HFTIPO"
	, HFCANTIDAD = "HFCANTIDAD"
	, HFGERMINACION = "HFGERMINACION" // https://huertify.atlassian.net/browse/HTFY-54
}
